# Generated by Django 5.0.4 on 2024-05-05 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.TextField(verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(verbose_name='Признак приятной привычки')),
                ('periodic', models.PositiveSmallIntegerField(verbose_name='Периодичность')),
                ('reward', models.TextField(verbose_name='Вознаграждение')),
                ('execute_time', models.PositiveSmallIntegerField(verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habits', verbose_name='Связанная привычка')),
            ],
        ),
    ]
