# Generated by Django 5.0.4 on 2024-05-06 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='action',
            field=models.CharField(max_length=120, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='is_pleasant',
            field=models.BooleanField(blank=True, null=True, verbose_name='Признак приятной привычки'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='is_public',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Признак публичности'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='place',
            field=models.CharField(max_length=120, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habits', verbose_name='Связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='reward',
            field=models.CharField(max_length=120, verbose_name='Вознаграждение'),
        ),
    ]
