# Generated by Django 5.0.4 on 2024-05-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habits_action_alter_habits_is_pleasant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habits',
            options={'ordering': ('-is_pleasant',), 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
    ]
