# Generated by Django 5.0.4 on 2024-05-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habits_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='reward',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Вознаграждение'),
        ),
    ]
