# Generated by Django 5.0.4 on 2024-05-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habits_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='last_notification',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последнее уведомление'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='is_pleasant',
            field=models.BooleanField(default=1, verbose_name='Признак приятной привычки'),
            preserve_default=False,
        ),
    ]
